// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 public/Armchair.glb 
// */

// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Armchair(props) {
//   const { nodes, materials } = useGLTF('/Armchair.glb');

//   console.log(props.color);
//   return (
//     <group  {...props} dispose={null}>
//       <mesh  geometry={nodes.Armchair.geometry} material={materials.Material} scale={100} />
//       <meshStandardMaterial              color={props.color || "#ffffff"}
//          // Brown color, you can use any hex color
//  roughness={0.5}
//           metalness={0.2}/>
//     </group>
//   )
// }

// useGLTF.preload('/Armchair.glb')

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Armchair(props) {
  const { nodes, materials } = useGLTF('/Armchair.glb')

  // Create a new material based on the original, but with the new color
  const coloredMaterial = new THREE.MeshStandardMaterial({
    ...materials.Material,
    color: new THREE.Color(props.color || "#ffffff"),
    // roughness: 0.5,
    // metalness: 0.2
  })

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Armchair.geometry} 
        material={coloredMaterial}
        scale={100} 
      />
    </group>
  )
}

useGLTF.preload('/Armchair.glb')